### ISSUE TITLE
Installation error when pasting the auto deploy

### ISSUE THREAD

**Issue by ryantechdev** [tommytran732/Pterodactyl-Script#15]
`Daemon installation is nearly complete, please go to the panel and get your 'Auto Deploy' command in the node configuration tab.

Paste your auto deploy command below:
cd /etc/pterodactyl && sudo wings configure --panel-url https://panel.(domain) --token (mytoken) --node 1

/dev/fd/63: line 1494: cd: too many arguments`

**Comment by hwalker928** [comment]
I have had this same error multiple of times trying to install wings.

I end up just running the auto deploy command in the terminal, then restarting or starting wings.

**Comment by tommytran732** [comment]
This is no longer applicable. The latest version no longer takes in the auto deployment command, so I am closing this one :)
