### ISSUE TITLE
The subdomain correctly redirects to the server and still the error message is displayed.

### ISSUE THREAD

**Issue by gamingnotice** [tommytran732/Pterodactyl-Script#18]
The entered domain does not resolve to the primary public IP of this server.
Please make an A record pointing to your server's IP. For example, if you make an A record called 'panel' pointing to your server's IP, your FQDN is panel.domain.tld
If you are using Cloudflare, please disable the orange cloud.
If you do not have a domain, you can get a free one at https://freenom.com
Please enter your FQDN (panel.domain.tld):

The subdomain correctly redirects to the server and still the error message is displayed.

**Comment by IdefixRC** [comment]
I tried to install my server today and ran into the same issue.
dig +short myip.opendns.com @resolver1.opendns.com show the correct public IP and I can see the domain resolves to the same, correct IP.

**Comment by tommytran732** [comment]
> I tried to install my server today and ran into the same issue.
> dig +short myip.opendns.com @resolver1.opendns.com show the correct public IP and I can see the domain resolves to the same, correct IP.
> 
> Update: managed to get it to work by replacing this line in the script:
> 
> SERVER_IP=$(curl -s http://checkip.amazonaws.com)
> with
> SERVER_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
> 
> Not sure why amazonaws didn't resolve to the correct address.

How long did you wait before you run the script? DNS may take time to propagate.

**Comment by IdefixRC** [comment]
> > I tried to install my server today and ran into the same issue.
> > dig +short myip.opendns.com @resolver1.opendns.com show the correct public IP and I can see the domain resolves to the same, correct IP.
> > Update: managed to get it to work by replacing this line in the script:
> > SERVER_IP=$(curl -s http://checkip.amazonaws.com)
> > with
> > SERVER_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
> > Not sure why amazonaws didn't resolve to the correct address.
> 
> How long did you wait before you run the script? DNS may take time to propagate.

You are correct of course Tommy. 8 hours later and amazon caught up.
Works fine now and thanks for the update to 1.0.3 !
I'm installing now. Fingers crossed ;-)

**Comment by tommytran732** [comment]
Okay, I am closing this issue since it's not really an issue with the script.
