### ISSUE TITLE
Install option 13 and 14 are mixed around

### ISSUE THREAD

**Issue by Spijkerpoepen** [tommytran732/Pterodactyl-Script#21]
Hey, I think I found a mistake in the pterodactyl script.

For option 13:
At line 171, it says `output "[13] Upgrade the panel to 1.0.3 and Migrate to wings"`
At line 2143-2147, it says
 `        13)  theme_options`
             `upgrade_pterodactyl_0.7.19` <--- this one should be `upgrade_pterodactyl_1.0`, I think
           `  theme`
           `  migrate_wings`
        `   ;;`

For option 14:
At line 172, it says `output "[14] Upgrade the panel to 0.7.19 and daemon to (0.6.13)"`
At line 2148-2152, it says
`        14)  theme_options`
            ` upgrade_pterodactyl_1.0` <--- this one should be `upgrade_pterodactyl_0.7.19`, I think
            ` theme`
          `   upgrade_daemon`
          `  ;;`

I feel like option 13 and 14 are mixed around, since option 14 contains upgrade_pterodactyl_1.0 but option 14 is for upgrading pterodactyl to 0.7.19.

**Comment by ryantechdev** [comment]
agreed

**Comment by ryantechdev** [comment]
@TheRealHeyJack hey can you fix this in #22

**Comment by TheRealHeyJack** [comment]
Fixed when #22 gets merged

**Comment by TheRealHeyJack** [comment]
Fixed in commit
