### ISSUE TITLE
MYSQL Error

### ISSUE THREAD

**Issue by Vpxgamer** [tommytran732/Pterodactyl-Script#26]
Hello,
Whenever I try to use the script to install mysql for nodes, it doesnt work.
I run the command, and use 19 for the option. In the panel, I add a database host with the info it told me, and I get an SQLSTATE[HY000] [2002] Connection refused (SQL: SELECT 1 FROM dual)  when i try to add the host. My panel is running ubuntu 18.04, with pterodactyl 1.0.3, and my node where i am trying to install mysql is ubuntu 20.04, with wings.

**Comment by tommytran732** [comment]
The option to do a standalone MariaDB database has been removed from the script, at least for now. This is no longer applicable, so I am closing this ticket.
