### ISSUE TITLE
Panel Upgrade not working

### ISSUE THREAD

**Issue by IdefixRC** [tommytran732/Pterodactyl-Script#38]
Hi, 

I have issues using the update procedure from 1.2.x Panel to latest (using option 8 in the script).
The script executes fine, no errors are produced but somehow the panel does not reflect the new version.
I had the same issue earlier from 1.1.x to 1.2.x and thought it was an issue with my installation so reinstalled Ubuntu 20 and used the script to install version 1.2.x fresh however when I now try to upgrade I have the same issue as before.

Could someone point me in the right direction on how to troubleshoot this issue?

Thanks !

**Comment by LilSadPanda** [comment]
> Hi, 
> 
> I have issues using the update procedure from 1.2.x Panel to latest (using option 8 in the script).
> The script executes fine, no errors are produced but somehow the panel does not reflect the new version.
> I had the same issue earlier from 1.1.x to 1.2.x and thought it was an issue with my installation so reinstalled Ubuntu 20 and used the script to install version 1.2.x fresh however when I now try to upgrade I have the same issue as before.
> 
> Could someone point me in the right direction on how to troubleshoot this issue?
> 
> Thanks !

Had the same problem with the script

**Comment by tommytran732** [comment]
Sorry for the late reply, I will look into this.

**Comment by kaname-png** [comment]
I have the same problem, the panel does not update, it continues in the same version.

**Comment by ThePedroo** [comment]
You can use cd /var/www/pterodactyl && php artisan p:upgrade for upgrade the panel for now

**Comment by tommytran732** [comment]
Should be fixed in the master branch. Please reopen if it's still an issue.
