### ISSUE TITLE
DataBase creation error

### ISSUE THREAD

**Issue by B3ndik0208** [tommytran732/Pterodactyl-Script#4]
`There was an error while trying to connect to the host or while executing a query: "SQLSTATE[HY000] [2002] Connection refused (SQL: SELECT 1 FROM dual)"` I get this when I try to add the database inside the panel after the script is finish installing

I press [1] on the firewall setup on both of them, its happends on ubuntu 18.04 and 20.04

**Comment by tommytran732** [comment]
I can reproduce this bug. Seems like this is caused by the unix_socket_authentication on newer versions of MariaDB. I will attempt to fix this in the next couple of days.

**Comment by LucidAPs** [comment]
I am having the same problem unfortunately. Any solutions?

**Comment by itsmemac** [comment]
@B3ndik0208 @LucidAPs try the steps below

- go to cd /etc/mysql/mariadb.conf.d
- and edit 50-server.cnf
- erase 127.0.0.1 and put 0.0.0.0
- save
- and restart mysql

Found this is Revenact Discord server months ago. It worked for me

**Comment by INfoUpgraders** [comment]
All that does is bind the port, not bypass the firewall.

**Comment by Wqrld** [comment]
Will see if i can reproduce and patch this.

**Comment by tommytran732** [comment]
Fixed in #8 and #9
