### ISSUE TITLE
syntax error near unexpected token `}' 

### ISSUE THREAD

**Issue by xkaasplakje** [tommytran732/Pterodactyl-Script#45]
**Note: for support questions, please use the [Discord](https://revenact.io/discord)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] Bug Report

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **[Pastebin](https://pastebin.com) link of the error**

https://pastebin.com/VH982zXZ

* **What is the expected behavior?**

It executes the script

* **What is the motivation / use case for changing the behavior?**

Well, the script will work

* **Please tell us about your environment:**

```
  - Version: v1.1.1
  - OS: Ubuntu 20.04
  - Install Options: -
```

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)*

**Comment by tommytran732** [comment]
Fixed. Thank you for your report!
