### ISSUE TITLE
PHPMyAdmin Installation Error

### ISSUE THREAD

**Issue by duranaaron** [tommytran732/Pterodactyl-Script#47]
**Note: for support questions, please use the [Discord](https://revenact.io/discord)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ x] Bug Report
  - [ ] Feature Request
  - [ ] Support Request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **[Pastebin](https://pastebin.com) link of the error**

https://pastebin.com/rCQqXdXi

* **What is the expected behavior?**

PHPMyAdmin installs succesfully.

* **What is the motivation / use case for changing the behavior?**

So it works again.

* **Please tell us about your environment:**

```
  - Version: v1.1.7
  - OS: Ubuntu 20.04.4
  - Install Options: 7 | Nginx
```

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

PHPMyAdmin just doesn't install, it gives the error "chown: cannot access '/var/lib/phpmyadmin/temp': No such file or directory"

**Comment by erwinowak** [comment]
the same problem

**Comment by NPCtom** [comment]
For Ubuntu 20.04 I used this guide: https://devanswers.co/install-secure-phpmyadmin-nginx-ubuntu-20-04/
I used Nginx for both the panel and phpMyAdmin, so make sure you press "tab" when selecting a web server as nginx is not listed during install. It's ill advised to use two web servers on one machine.

**Comment by tommytran732** [comment]
I will have a new version in a few days, and I will be dropping Ubuntu & Debian support, so I am closing this. (I'd like to just support a few distributions but support them well rather than having a bunch of bugs to deal with xd... plus managing dependency versions with apt is much more annoying than with dnf modular repos)
