### ISSUE TITLE
error ssl

### ISSUE THREAD

**Issue by francoav** [tommytran732/Pterodactyl-Script#49]
* **I'm submitting a ...**
  - [*] Bug Report
  - [ ] Feature Request
  - [ ] Support Request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

error ssl service no working

* **[Pastebin](https://pastebin.com) link of the error**

![image](https://user-images.githubusercontent.com/20564414/168179595-555eecbc-89c2-437c-bb29-c7c72a78800f.png)

install panel

* **Please tell us about your environment:**

```
  - Version: v1.1.18
  - OS: [Ubuntu 20  | CentOS 8  ]
  - Install Options: [1-22 | Apache, Nginx | Theme ]
```

**Comment by tommytran732** [comment]
Are you sure you type in the hostname correctly?
If you are not willing to make the FQDN public, do you mind sending me a message on Matrix about this?

**Comment by tommytran732** [comment]
Should be fixed
