### ISSUE TITLE
Support: RHEL 9.1

### ISSUE THREAD

**Issue by IdefixRC** [tommytran732/Pterodactyl-Script#51]
Hi there,

Can someone point me to the docu describing the required base OS configuration for RHEL 9.1 for the script to work?
I have so far not managed to get the server online using the script (throws a number of errors during installation, cannot find certain dependencies). I assume I must be missing something when I install the base OS before running the script (past installations on Ubuntu, when the script still supported it, worked like a charm).

Thanks !

**Comment by tommytran732** [comment]
Fixed in the latest release
