### ISSUE TITLE
Servers not installing

### ISSUE THREAD

**Issue by wildmaster84** [tommytran732/Pterodactyl-Script#7]
OS: Ubuntu 20.04.1

I tried creating 1 minecraft server and 1 discord bot and i left for XCountry and when i got back the server was still showing installing, i made sure it wasn't the eggs so idk what's causing the issue

**Comment by wildmaster84** [comment]
![image](https://user-images.githubusercontent.com/46942741/92190772-f5a00500-ee2f-11ea-8671-7945f9f85605.png)

**Comment by markd69** [comment]
This is unrelated to Tommy’s script. Should be taken up with pterodactyl.

**Comment by wildmaster84** [comment]
I talked to pterodactyl and they said it was caused by broken packages, the only thing i used before anything broke WAS this script and thanks to it, i lost 5 website and 2 years of work. This issue is not related with pterodactyl but they way the script installs the packages.

**Comment by markd69** [comment]
I don’t see how it is related to packages? Did you run the script on a fresh system?

**Comment by wildmaster84** [comment]
Yes its on a fresh install of Ubuntu 20.04. ;-;

**Comment by wildmaster84** [comment]
I figured out what the issue is, while running the script the first time, it randomly ejects drives which in my case it ejected the main drive and caused it to corrupt the boot sector, ii's still not very clear on what caused it but after running the script 5 times it sorted it's self out (On the new OS that is) I now run the 1.0beta version of the panel and i wont be trying to install the daemon as well as it broke npm.

**Comment by tommytran732** [comment]
> 
> 
> I talked to pterodactyl and they said it was caused by broken packages, the only thing i used before anything broke WAS this script and thanks to it, i lost 5 website and 2 years of work. This issue is not related with pterodactyl but the way the script installs the packages.

The script clearly states that it is meant to run on a fresh system, it is your fault for running it on systems that already has stuff preinstalled. 

> 
> 
> Yes its on a fresh install of Ubuntu 20.04. ;-;

If it was on a fresh system, how did you lose your work???

> 
> 
> I figured out what the issue is, while running the script the first time, it randomly ejects drives which in my case it ejected the main drive and caused it to corrupt the boot sector, it's still not very clear on what caused it but after running the script 5 times it sorted it's self out (On the new OS that is) I now run the 1.0beta version of the panel and i wont be trying to install the daemon as well as it broke npm.

Version 1.0 is NOT ready for production. I will not be supporting it until it is. You are on your own here.
